spring:
  datasource:
    url: jdbc:mysql://localhost:3306/businessmodels?createDatabaseIfNotExist=true
    username: root
    password: vivek#qwer
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: create-drop

server:
  port: 9193